// components/Layout/SocialMedia/index.tsx
import type { NextPage } from "next";
import { motion } from "framer-motion";
import Item from "./Item";
import Github from "assets/icons/github.svg";
import Linkedin from "assets/icons/linkedin.svg";
import Twitter from "assets/icons/twitter.svg";
import Instagram from "assets/icons/instagram.svg";
import Telegram from "assets/icons/telegram.svg";
import Mail from "assets/icons/mail.svg";

const SocialMedia: NextPage = () => {
  const items: { url: string; name: string; icon: any }[] = [
    {
      url: "https://github.com/mortezasabihi",
      name: "github",
      icon: <Github />,
    },
    {
      url: "https://www.linkedin.com/in/mortezasabihi",
      name: "linkedin",
      icon: <Linkedin />,
    },
    {
      url: "https://twitter.com/mortezasabihi",
      name: "twitter",
      icon: <Twitter />,
    },
    {
      url: "https://www.instagram.com/mortezasabihi",
      name: "instagram",
      icon: <Instagram />,
    },
    {
      url: "https://t.me/mortezasabihi",
      name: "telegram",
      icon: <Telegram />,
    },
    {
      url: "mailto:morteza.sabihi@gmail.com",
      name: "email",
      icon: <Mail />,
    },
  ];

  return (
    <motion.div
      initial={{ y: -30, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ delay: 1.5, duration: 0.4 }}
      className="mb-20 mx-auto lg:max-w-sm"
    >
      <div className="text-center tracking-widest font-bold mb-6">
        Find me on:
      </div>

      <div className="flex items-center justify-between">
        {items.map((item, index) => (
          <Item key={index} href={item.url}>
            {item.icon}
            <span className="sr-only">{item.name}</span>
          </Item>
        ))}
      </div>
    </motion.div>
  );
};

export default SocialMedia;

// components/layout/SocialMedia.vue
<template>
  <div class="mb-20 mx-auto lg:max-w-sm animate__animated animate__fadeInUp">
    <div class="text-center tracking-widest font-bold mb-6">
      Stay in touch with me on:
    </div>

    <div class="flex items-center justify-between flex-row-reverse">
      <a
        v-for="(item, index) in items"
        :key="index"
        :href="item.url"
        target="_blank"
        class="w-12 h-12 flex items-center justify-center rounded-full hover:bg-white focus:bg-white text-lg transform hover:scale-150 focus:scale-150 transition ease-in-out duration-150"
      >
        <font-awesome-icon :icon="['fab', item.icon]" />
      </a>
    </div>
  </div>
</template>

<script>
export default {
  name: 'SocialMedia',
  data() {
    return {
      items: [
        { icon: 'telegram-plane', url: 'https://t.me/mortezasabihi' },
        { icon: 'instagram', url: 'https://www.instagram.com/morteza.sabihi' },
        { icon: 'twitter', url: 'https://twitter.com/mortezasabihi' },
        {
          icon: 'linkedin-in',
          url: 'https://ir.linkedin.com/in/mortezasabihi',
        },
        { icon: 'github', url: 'https://github.com/mortezasabihi' },
      ],
    }
  },
}
</script>
