// pages/index.vue
<template>
  <div>
    <Hero />
  </div>
</template>

<script>
export default {
  name: 'IndexPage',
  head: {
    meta: [
      {
        property: 'og:url',
        content: 'https://mortezasabihi.com',
      },
      {
        name: 'og:title',
        property: 'og:title',
        content: "Morteza Sabihi's personal website ← Morteza Sabihi",
      },
      {
        name: 'og:description',
        property: 'og:description',
        content: "Morteza Sabihi's personal website",
      },
      {
        name: 'twitter:title',
        content: "Morteza Sabihi's personal website ← Morteza Sabihi",
      },
      {
        name: 'twitter:description',
        content: "Morteza Sabihi's personal website",
      },
      {
        itemprop: 'name',
        content: "Morteza Sabihi's personal website ← Morteza Sabihi",
      },
      {
        itemprop: 'description',
        content: "Morteza Sabihi's personal website",
      },
    ],
    link: [{ rel: 'canonical', href: 'https://mortezasabihi.com' }],
  },
  transition: {
    enterActiveClass: 'animate__animated animate__fadeIn',
    leaveActiveClass: 'animate__animated animate__fadeOut animate__faster',
  },
}
</script>

// pages/index.tsx
import type { NextPage, GetStaticProps } from "next";
import Head from "next/head";
import { Hero } from "components";
import { Github } from "types";
import { getGithub } from "services";

type Props = {
  github: Github;
};

const Home: NextPage<Props> = ({ github }) => {
  return (
    <>
      <Head>
        <title>{github.name}</title>
        <meta property="og:title" name="og:title" content={github.name} />
        <meta
          property="og:url"
          name="og:url"
          content="https://mortezasabihi.com"
        />
        <meta property="og:image" name="og:image" content={github.avatar_url} />
        <meta
          property="og:description"
          name="og:description"
          content="Morteza Sabihi's personal website"
          key="description"
        />
        <meta
          property="twitter:title"
          name="twitter:title"
          content={github.name}
        />
        <meta
          property="twitter:image"
          name="twitter:image"
          content={github.avatar_url}
        />
        <meta
          property="twitter:description"
          name="twitter:description"
          content="Morteza Sabihi's personal website"
        />
        <meta itemProp="name" content={github.name} />
        <meta
          itemProp="description"
          content="Morteza Sabihi's personal website"
        />
        <link rel="canonical" href="https://mortezasabihi.com" />
      </Head>

      <Hero avatar_url={github.avatar_url} hireable={github.hireable} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const data = await getGithub();

  return {
    props: {
      github: data,
    },
  };
};
