// components/pages/resume/educations/index.vue
<template>
  <div class="mb-8">
    <!-- title -->
    <h3 class="text-2xl font-bold border-b-2 border-black pb-2 mb-4">
      Education
    </h3>
    <!-- /title -->

    <!-- ediucations -->
    <PageResumeEducationsItem
      title="Islamic Azad University, Parand Branch"
      date="2020"
      degree="Bachelor's degree, Computer Engineering"
    />
    <PageResumeEducationsItem
      title="Noorani poor"
      date="2017 - 2019"
      degree="High School Diploma, Computer Science"
    />
    <!-- ediucations -->
  </div>
</template>

<script>
export default {
  name: 'Educations',
}
</script>

// components/Page/Resume/Educations/index.tsx
import { Education } from "types";
import Item from "./Item";

const Educations = () => {
  const educations: Education[] = [
    {
      title: "Noorani poor",
      date: "2017 - 2019",
      degree: "High School Diploma, Computer Science",
    },
    {
      title: "Islamic Azad University, Parand Branch",
      date: "2020",
      degree: "Bachelor's degree, Computer Engineering",
    },
  ];

  return (
    <div className="mb-8">
      <h2 className="section-heading">Education</h2>

      {educations.reverse().map((education, index) => (
        <Item
          key={index}
          title={education.title}
          date={education.date}
          degree={education.degree}
        />
      ))}
    </div>
  );
};

export default Educations;
